from ex0 import FlameFactory, AquaFactory

if __name__ == "__main__":
    print("Testing factory")
    flamefact = FlameFactory()
    flaming = flamefact.create_base()
    print(flaming.describe())
    print(flaming.attack())
    pyrodon = flamefact.create_evolved()
    print(pyrodon.describe())
    print(pyrodon.attack())
    print("\nTesting factory")
    waterfact = AquaFactory()
    water = waterfact.create_base()
    print(water.describe())
    print(water.attack())
    torragon = waterfact.create_evolved()
    print(torragon.describe())
    print(torragon.attack())
    print("\nTesting battle")
    print(flaming.describe())
    print("vs.")
    print(water.describe())
    print("fight!")
    print(flaming.attack())
    print(water.attack())
