from ex1 import HealingCreatureFactory, TransformCreatureFactory

if __name__ == "__main__":
    print("Testing Creature with healing capability")
    print("base:")
    healfact = HealingCreatureFactory()
    sproutling = healfact.create_base()
    print(sproutling.describe())
    print(sproutling.attack())
    print(sproutling.heal("itself"))
    print("evolved:")
    bloomelle = healfact.create_evolved()
    print(bloomelle.describe())
    print(bloomelle.attack())
    print(bloomelle.heal("itself and others"))
    print("\nTesting Creature with transform capability")
    print("base:")
    transfact = TransformCreatureFactory()
    shiftling = transfact.create_base()
    print(shiftling.describe())
    print(shiftling.attack())
    print(shiftling.transform())
    print(shiftling.attack())
    print(shiftling.revert())
    print("evolved:")
    morphagon = transfact.create_evolved()
    print(morphagon.describe())
    print(morphagon.attack())
    print(morphagon.transform())
    print(morphagon.attack())
    print(morphagon.revert())
